set(OPENSSL_LIB_CRYPTO
    ${OPENSSL_BUILD_INSTALL_ROOT}${OPENSSL_PREFIX_OPENSSLDIR}/lib/libcrypto${CMAKE_SHARED_LIBRARY_SUFFIX})
set(OPENSSL_LIB_SSL
    ${OPENSSL_BUILD_INSTALL_ROOT}${OPENSSL_PREFIX_OPENSSLDIR}/lib/libssl${CMAKE_SHARED_LIBRARY_SUFFIX})

add_library(
    OpenSSL_crypto_shared SHARED IMPORTED GLOBAL)
add_library(
    OpenSSL_ssl_shared SHARED IMPORTED GLOBAL)

set_target_properties(
    OpenSSL_crypto_shared PROPERTIES IMPORTED_LOCATION ${OPENSSL_LIB_CRYPTO})
set_target_properties(
    OpenSSL_ssl_shared PROPERTIES IMPORTED_LOCATION ${OPENSSL_LIB_SSL})

set_property(GLOBAL PROPERTY openssl_build_install_dir_property ${OPENSSL_BUILD_INSTALL_ROOT}${OPENSSL_PREFIX_OPENSSLDIR})
